### ISSUE TITLE
Add page dividers

### ISSUE THREAD

**Issue by inwhitemist** [inwhitemist/timeline#5]

**Comment by inwhitemist** [comment]
Чтобы добавить разделители между секциями (постами) на вашем сайте, вам нужно внести некоторые изменения в HTML и CSS. Вот пример:

1. **HTML:**
Обновите структуру секций, добавив элемент `<hr>` для разделителя между постами:

```html
<!DOCTYPE html>
<html>
<head>
  <!-- ваш заголовок и другие элементы заголовка -->
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <nav id="sidebar">
    <ul>
      <li><a href="#may-2023">Май 2023</a></li>
      <!-- Добавьте ссылки на другие месяцы и года -->
    </ul>
  </nav>

  <div id="content">
    <!-- Остальное содержимое страницы, включая секции с месяцами и годами -->
    <section id="may-2023">
      <h2>Май 2023</h2>
      <!-- Содержимое секции -->
      <p>Содержимое поста для мая 2023 года.</p>
      <hr> <!-- Разделитель -->
    </section>
    <!-- Другие секции с месяцами и годами -->
  </div>
</body>
</html>
```

2. **CSS (styles.css):**
Добавьте стили для разделителя:

```css
/* ... (ваш существующий CSS) */

#content hr {
  margin: 20px 0; /* Устанавливаем отступы для разделителя */
  border: 1px solid #ccc; /* Стиль и цвет разделителя */
}
```

Теперь между каждой секцией будет отображаться горизонтальный разделитель. При необходимости вы можете настроить стили разделителя, устанавливая другой цвет, толщину или отступы.
