### ISSUE TITLE
Add anchors to classes

### ISSUE THREAD

**Issue by inwhitemist** [inwhitemist/timeline#7]

**Comment by inwhitemist** [comment]
Конечно, чтобы создать небольшое меню справа с ссылками для якорей, вам нужно внести некоторые изменения в HTML и CSS. Вот пример:

1. **HTML:**
Добавьте меню справа, содержащее ссылки на якори:

```html
<!DOCTYPE html>
<html>
<head>
  <!-- ваш заголовок и другие элементы заголовка -->
  <link rel="stylesheet" type="text/css" href="styles.css">
</head>
<body>
  <nav id="sidebar">
    <ul>
      <li><a href="#may-2023">Май 2023</a></li>
      <!-- Добавьте ссылки на другие месяцы и года -->
    </ul>
  </nav>

  <div id="content">
    <!-- Остальное содержимое страницы, включая секции с месяцами и годами -->
    <section id="may-2023">
      <h2>Май 2023</h2>
      <!-- Содержимое секции -->
    </section>
    <!-- Другие секции с месяцами и годами -->
  </div>
</body>
</html>
```

2. **CSS (styles.css):**
Добавьте стили для бокового меню и контента:

```css
body {
  display: flex;
}

#sidebar {
  width: 20%;
  background-color: #f0f0f0;
  padding: 20px;
}

#sidebar ul {
  list-style-type: none;
  padding: 0;
}

#sidebar li {
  margin-bottom: 10px;
}

#sidebar a {
  text-decoration: none;
  color: #000;
}

#content {
  width: 80%;
  padding: 20px;
}
```

Теперь у вас есть боковое меню с ссылками на якори. Когда пользователь кликает на ссылку, страница будет плавно скроллиться к соответствующей секции. Убедитесь, что у секций имеются уникальные идентификаторы (например, "may-2023"), соответствующие якорям в ссылках.
